#
# bundle exec jekyll serve --config "_config.yml,_config_dev.yml"  --incremental
#
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ideas
tagline:          'Cause a Scene'
description:      'A collection of ideas compiled by <a href="https://twitter.com/realdavidawad" target="_blank">@realdavidawad</a>.'
url:              http://davidawad.com
baseurl:          /

project-images: public/img/projects
imageoptim:
  svgo: false
  verbose: false

# css compression hopefully
sass:
  style: compressed

assets:
  digest: true
  defaults:
    js: {integrity: true} # true on JEKYLL_ENV=production
    css: {integrity: true} # true on JEKYLL_ENV=production
    img: {integrity: true} # true on JEKYLL_ENV=production

author:
  name:           'David Awad'
  url:            https://twitter.com/realdavidawad


paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/davidawad/blog

# Gems
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-offline
  - jekyll-compress-images


# bitcoin pubkey address
pubkey: 1gtRkH3399UipceRUG2xWRyYsYQk84SFM

sendgrid_key: SENDGRID_ENV

links:
  email:     me@davidawad.com
  fb:        https://fb.com/david.a.awad
  twitter:   https://twitter.com/realdavidawad
  instagram:   https://instagram.com/realdavidawad
  spotify:   https://open.spotify.com/user/1253499829
  angellist: https://angel.co/davidawad
  github:    https://github.com/davidawad
  linkedin:  https://linkedin.com/in/davidawad64
  so:        https://stackoverflow.com/users/2178438/davidawad

# for jekyll-seo
twitter:
  username: realdavidawad

# TODO maybe breaking build for jekyll-offline
# offline:
  # strategy: cache-first-network-fallback

social:
  name: David Awad
  links:
    - https://twitter.com/realdavidawad
    - https://www.facebook.com/david.a.awad
    - https://www.linkedin.com/in/davidawad64
    - https://plus.google.com/+davidawad64
    - https://github.com/davidawad
    - https://instagram.com/_davidawad
    - https://stackoverflow.com/users/2178438/davidawad

## jekyll archives configuration
jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tag

  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: tag-archive

  permalinks:
    year:  /:year/
    month: /:year/:month/
    day:   /:year/:month/:day/
    tag:   /tag/:name/


# compress_html:
  # clippings: []
  # comments: []
  # endings: []
  # ignore:
    # envs: []
  # blanklines: false
  # profile: false
  # startings: []


# jekyll compilation time speedup by ignoring files
exclude:
    - _site
    - _assets
